import request from './request'
export const getUserList = params => request.get('/permission/users', { params })
export const getUser = id => request.get(`/permission/users/${id}`)
export const addUser = data => request.post('/permission/users', data)
export const updateUser = data => request.put('/permission/users', data)
export const deleteUser = id => request.delete(`/permission/users/${id}`)
export const updateUserStatus = (id, status) => request.put(`/permission/users/${id}/status/${status}`)
export const getRoleList = params => request.get('/permission/roles', { params })
export const getRole = id => request.get(`/permission/roles/${id}`)
export const addRole = data => request.post('/permission/roles', data)
export const updateRole = data => request.put('/permission/roles', data)
export const deleteRole = id => request.delete(`/permission/roles/${id}`)
export const getMenuList = params => request.get('/permission/menus', { params })
export const getMenu = id => request.get(`/permission/menus/${id}`)
export const addMenu = data => request.post('/permission/menus', data)
export const updateMenu = data => request.put('/permission/menus', data)
export const deleteMenu = id => request.delete(`/permission/menus/${id}`)
export const getDeptList = params => request.get('/permission/depts', { params })
export const getDept = id => request.get(`/permission/depts/${id}`)
export const addDept = data => request.post('/permission/depts', data)
export const updateDept = data => request.put('/permission/depts', data)
export const deleteDept = id => request.delete(`/permission/depts/${id}`)
